<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

    <!--<TargetFramework>net48</TargetFramework>-->
    <TargetFrameworks>net10.0-windows;net6.0-windows;netstandard2.0</TargetFrameworks>
 <!--Qud support requires netstandard2.0, bep6 requires net6. net48 is for testing the netstandard2.0 version.-->
 <!--<ImplicitUsings>enable</ImplicitUsings>-->
    <AppendRuntimeIdentifierToOutputPath>true</AppendRuntimeIdentifierToOutputPath>
    <SelfContained>false</SelfContained>
    <Prefer32Bit>false</Prefer32Bit>
    <LangVersion>9.0</LangVersion> 
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies> 
    <Configurations>Release;IApp;Debug</Configurations>
  <!-- <GenerateDocumentationFile>true</GenerateDocumentationFile> 
      <NoWarn>$(NoWarn);1591</NoWarn>--> 
  <!--  <TreatWarningsAsErrors>true</TreatWarningsAsErrors>-->
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' != 'netstandard2.0'">
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
     <!-- <LangVersion>11.0</LangVersion> -->
  </PropertyGroup>

  <PropertyGroup Condition="$(LangVersion) == '11.0' Or $(LangVersion) == 'latest'"> <!--There are some lang features I miss from C# 11, such as static abstract interface methods, but right now we dont really use this constant-->
    <DefineConstants>$(DefineConstants);CSHARP_11_OR_GREATER</DefineConstants> <!--As you can see there is no setting to compile Net6+ into C# 11 as of right now-->
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <!--  <LangVersion>9.0</LangVersion>-->
    <!--  <PackageReference Include="System.Collections.Immutable" Version="6.0.0" />-->
  </PropertyGroup>

<PropertyGroup Condition="'$(Configuration)' != 'Debug'">
  <Optimize>true</Optimize>
  <DebugSymbols>false</DebugSymbols>
  <DebugType>none</DebugType>
</PropertyGroup>

<PropertyGroup Condition="'$(Configuration)' != 'Release'">
  <OutputType>Exe</OutputType>
  <TargetFramework>net10.0-windows</TargetFramework>
</PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'IApp'">
    <OutputPath>bin\IApp\</OutputPath>
    <DefineConstants>$(DefineConstants);IAPP_BUILD</DefineConstants>
  </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
      <OutputPath>bin\Release\</OutputPath>
      <OutputType>Library</OutputType>
      <DefineConstants>$(DefineConstants);RELEASE_BUILD</DefineConstants>
  </PropertyGroup>


    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
      <OutputPath>bin\Debug\</OutputPath>
      <DefineConstants>$(DefineConstants);DEBUG_BUILD</DefineConstants>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
  <!--<PackageReference Include="Mono.Cecil" Version="0.9.4" Condition="'$(Configuration)' == 'Debug'"/>-->
    <PackageReference Include="Mono.Reflection" Version="2.0.0" /> 
    <!--sys collections immutable 6.0.0-->
  </ItemGroup>

</Project>
